version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      prod-dependencies:
        dependency-type: 'production'
        exclude-pattern:
          - 'mongo*'
          - 'rails'
      dev-dependencies:
        dependency-type: 'development'
      rails:
        pattern: 'rails'
      mongo:
        pattern: 'mongo*'
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
